name = "antelier-acceptance-testbed"
main = "worker.mjs"
compatibility_date = "2026-09-10"
workers_dev = true
preview_urls = true

[[rules]]
type = "Text"
globs = ["**/*.html"]
fallthrough = true

[observability]
enabled = false
